# -*- coding: utf-8 -*-
"""DS_&_ML_TASK_NO_5_MANISH_KUMAR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NjH_A0NUdav2tnzRvHjIhqGqFQhUGx_r
"""

# Import necessary libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('tested.csv')

# Display first few rows
df.head()

# Check the data types
print("\nData Types in the Dataset:")
print(df.dtypes)

# Check for missing values
print("\nMissing Values in the Dataset:")
print(df.isnull().sum())

# Add a synthetic datetime column
df['date'] = pd.date_range(start='2023-01-01', periods=len(df), freq='D')

# Set the "date" column as the index
df.set_index('date', inplace=True)

# Confirm the new column
print("\nDataset with Synthetic Datetime Column:")
print(df.head())

# Select only numeric columns
numeric_columns = df.select_dtypes(include=['float64', 'int64']).columns

# Display numeric columns
print("\nNumeric Columns:")
print(numeric_columns)

# Fill missing values in numeric columns with the column mean
df[numeric_columns] = df[numeric_columns].fillna(df[numeric_columns].mean())

# Confirm no missing values remain in numeric columns
print("\nMissing Values After Imputation (Numeric Columns):")
print(df[numeric_columns].isnull().sum())

# Resample numeric data to calculate weekly averages
weekly_data = df[numeric_columns].resample('W').mean()

# Display the resampled data
print("\nWeekly Resampled Data:")
print(weekly_data.head())

# Calculate rolling mean and rolling standard deviation for the first numeric column
target_column = numeric_columns[0]
df['rolling_mean'] = df[target_column].rolling(window=7).mean()
df['rolling_std'] = df[target_column].rolling(window=7).std()

# Display rolling statistics
print("\nRolling Statistics:")
print(df[['rolling_mean', 'rolling_std']].head(10))

# Create lagged features for the first numeric column
df['lag_1'] = df[target_column].shift(1)
df['lag_7'] = df[target_column].shift(7)

# Display lagged features
print("\nLagged Features:")
print(df[['lag_1', 'lag_7']].head(10))

import matplotlib.pyplot as plt

# Plot original data, rolling mean, and rolling standard deviation
plt.figure(figsize=(14, 7))
plt.plot(df[target_column], label='Original Data', color='blue')
plt.plot(df['rolling_mean'], label='Rolling Mean (7 days)', color='red')
plt.plot(df['rolling_std'], label='Rolling Std (7 days)', color='green')
plt.legend()
plt.title('Time Series Analysis')
plt.xlabel('Date')
plt.ylabel('Value')
plt.show()

# Export the final dataset to a CSV file
df.to_csv("processed_time_series.csv", index=True)
print("\nProcessed Dataset Exported as 'processed_time_series.csv'")

