# -*- coding: utf-8 -*-
"""DS_&_ML_TASK_NO_4_MANISH_KUMAR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HRGLI2BFoRo2ZwucEiTYi8OV8wf_Jh9_
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from matplotlib.colors import ListedColormap

# Load Wine Quality dataset from Kaggle
df = pd.read_csv('winequality-red.csv')

# Display first few rows
df.head()

# Check for missing values
print("\nMissing Values:\n", df.isnull().sum())

# If there were missing values, we could fill them or drop rows. For simplicity, let's assume there are no missing values.

# Standardize features (important for visualizing)
scaler = StandardScaler()
df_scaled = pd.DataFrame(scaler.fit_transform(df.drop('quality', axis=1)), columns=df.columns[:-1])

# Add the 'quality' column back to the scaled dataframe
df_scaled['quality'] = df['quality']

# Create a custom colormap using a list of colors
colors = ['#ff9999', '#ff6666', '#ff3333', '#ff0000', '#990000', '#660000', '#330000', '#000000', '#0000ff', '#3399ff']

# Define custom colormap
cmap = ListedColormap(colors)

# Create a scatter plot for the first two features with the custom colormap
plt.figure(figsize=(10, 6))
plt.scatter(df_scaled.iloc[:, 0], df_scaled.iloc[:, 1], c=df_scaled['quality'], cmap=cmap, s=50)
plt.title("Wine Quality vs Fixed Acidity and Volatile Acidity with Custom Colormap", fontsize=14)
plt.xlabel('Fixed Acidity')
plt.ylabel('Volatile Acidity')
plt.colorbar(label='Wine Quality')
plt.show()

# Create a heatmap of all features with custom colormap
plt.figure(figsize=(12, 8))
sns.heatmap(df_scaled.drop('quality', axis=1).corr(), annot=True, cmap=cmap)
plt.title("Correlation Heatmap of Features with Custom Colormap", fontsize=14)
plt.show()

